### ISSUE TITLE
ValidationError: child "password" fails because ["password" is required]

### ISSUE THREAD

**Issue by martinoppitz** [jsperf/jsperf.com#160]
Where is the problem?

```bash
λ npm start DB_ENV_MYSQL_PASSWORD=jsperf DB_ENV_MYSQL_DATABASE=jsperf DB_ENV_MYSQL_USER=jsperf

> jsperf.com@2.0.0 start C:\Users\moz\Workspace\jsperf.com
> node server.js "DB_ENV_MYSQL_PASSWORD=jsperf" "DB_ENV_MYSQL_DATABASE=jsperf" "DB_ENV_MYSQL_USER=jsperf"

160820/033357.074, [log,debug] data: registering auth strategies
C:\Users\moz\Workspace\jsperf.com\node_modules\hapi-auth-cookie\node_modules\hoek\lib\index.js:717
        throw arguments[1];
        ^

ValidationError: child "password" fails because ["password" is required]
    at Object.internals.Err.toString.exports.process (C:\Users\moz\Workspace\jsperf.com\node_modules\hapi-auth-cookie\node_modules\joi\lib\errors.js:141:19)
    at internals.Any.applyFunctionToChildren.internals.Any._validateWithOptions (C:\Users\moz\Workspace\jsperf.com\node_modules\hapi-auth-cookie\node_modules\joi\lib\any.js:645:27)
    at root.validate (C:\Users\moz\Workspace\jsperf.com\node_modules\hapi-auth-cookie\node_modules\joi\lib\index.js:103:23)
    at Object.internals.implementation.server.ext [as cookie] (C:\Users\moz\Workspace\jsperf.com\node_modules\hapi-auth-cookie\lib\index.js:44:25)
    at internals.Auth.strategy (C:\Users\moz\Workspace\jsperf.com\node_modules\hapi\lib\auth.js:51:43)
    at module.exports.internals.Plugin.parent.auth.internals.Plugin.register.internals.Plugin._applyChild (C:\Users\moz\Workspace\jsperf.com\node_modules\hapi\lib\plugin.js:584:19)
    at Object.auth.default.scheme.strategy (C:\Users\moz\Workspace\jsperf.com\node_modules\hapi\lib\plugin.js:64:54)

    at Object.exports.register (C:\Users\moz\Workspace\jsperf.com\server\web\auth\strategies.js:4:15)
    at Object.target [as register] (C:\Users\moz\Workspace\jsperf.com\node_modules\joi\lib\object.js:77:34)
    at each (C:\Users\moz\Workspace\jsperf.com\node_modules\hapi\lib\plugin.js:317:14)

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\moz\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start" "DB_ENV_MYSQL_PASSWORD=jsperf" "DB_ENV_MYSQL_DATABASE=jsperf" "DB_ENV_MYSQL_USER=jsperf"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! jsperf.com@2.0.0 start: `node server.js "DB_ENV_MYSQL_PASSWORD=jsperf" "DB_ENV_MYSQL_DATABASE=jsperf" "DB_ENV_MYSQL_USER=jsperf"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jsperf.com@2.0.0 start script 'node server.js "DB_ENV_MYSQL_PASSWORD=jsperf" "DB_ENV_MYSQL_DATABASE=jsperf" "DB_ENV_MYSQL_USER=jsperf"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the jsperf.com package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js "DB_ENV_MYSQL_PASSWORD=jsperf" "DB_ENV_MYSQL_DATABASE=jsperf" "DB_ENV_MYSQL_USER=jsperf"

npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs jsperf.com
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls jsperf.com
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\moz\Workspace\jsperf.com\npm-debug.log
```

**Comment by madskonradsen** [comment]
It fails because you didn't, as the instructions illustrate, put the env-variables before `npm start`

Like: `DB_ENV_MYSQL_PASSWORD=jsperf DB_ENV_MYSQL_DATABASE=jsperf DB_ENV_MYSQL_USER=jsperf npm start`

**Comment by martinoppitz** [comment]
I do.

I have a `.env` file.
```txt
DB_ENV_MYSQL_PASSWORD=jsperf
DB_ENV_MYSQL_DATABASE=jsperf
DB_ENV_MYSQL_USER=jsperf
```

**Works**
```bash
λ node setup/tables.js DB_ENV_MYSQL_PASSWORD=jsperf DB_ENV_MYSQL_DATABASE=jsperf DB_ENV_MYSQL_USER=jsperf
```

**Fault**
```bash
λ npm start DB_ENV_MYSQL_PASSWORD=jsperf DB_ENV_MYSQL_DATABASE=jsperf DB_ENV_MYSQL_USER=jsperf
```

**Comment by madskonradsen** [comment]
Do you have BELL_COOKIE_PASS and COOKIE_PASS?

**Comment by martinoppitz** [comment]
I dont know. How can I verify this?

**Comment by madskonradsen** [comment]
By looking at your .env-file. It looks like it fails in the "hapi-auth-cookie"-module, which could indicate something along the lines of a missing cookie-pass

**Comment by martinoppitz** [comment]
Maybe. But how can I fix the problem. The DB is initializierd. But the `npm start` do not the same as 'node setup/tables.js'.

**Comment by maxbeatty** [comment]
`node setup` should populate your `.env` with everything you need
