### ISSUE TITLE
🔥Site down

### ISSUE THREAD

**Issue by gdibble** [jsperf/jsperf.com#538]
Response for homepage etcetera
```
A server error has occurred
500: INTERNAL_SERVER_ERROR
Code: FUNCTION_INVOCATION_FAILED
ID: sfo1::gdg9v-1614924152430-6f6450c1ce11
```

**Comment by kapik** [comment]
Project down ?

**Comment by djatwood** [comment]
It looks like a dependency error? [Logs](https://vercel.com/jsperf/jsperf.com/7xA184KQkgb2TaNy1dkn266qj3zi/functions)
`
2021-03-15T18:16:06.982Z	undefined	ERROR	Cannot find module 'hapi-qs'Require stack:- /var/task/node_modules/glue/lib/index.js- /var/task/index.js- /var/task/server.js- /var/task/___now_launcher.js- /var/runtime/UserFunction.js- /var/runtime/index.js2021-03-15T18:16:06.982Z	undefined	ERROR	Did you forget to add it to "dependencies" in `package.json`?RequestId: 531b34c7-1a1e-4ce1-838a-2aa06265cffe Error: Runtime exited with error: exit status 1Runtime.ExitError
`

**Comment by gdibble** [comment]
Looks like we have `hapi-qs` in the package.json
https://github.com/jsperf/jsperf.com/blob/c8e41c2598235b4d7e14474689c9ca44a4c20451/package.json#L51

~~

Upon running `npm i` I got this error:
`npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.`

I tried downgrading the dev-dep with `npm i ajv@^5 --save-dev` (from ^6.12.6 to ^5.5.2)
Running `npm i` then resulted in:
`npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})`

I tried running the project with this unfortunate windoze error:
```
$ npm start

> jsperf.com@2.0.0 start D:\dev\jsperf.com
> node server.js

D:\dev\jsperf.com\config.js:40
  throw new Error(`${result.error.details[0].path[0]} environment variable is missing`);
  ^

Error: GITHUB_CLIENT_SECRET environment variable is missing
    at Object.<anonymous> (D:\dev\jsperf.com\config.js:40:9)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (D:\dev\jsperf.com\manifest.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jsperf.com@2.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jsperf.com@2.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

I'm blocked by my OS.  Can anyone else try/verify?  Thanks
